services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_WEB:-15672}:15672"
    networks:
      - trafego

  chaos:
    build: ./chaos
    container_name: chaos
    privileged: true
    network_mode: "service:rabbitmq"
    depends_on:
      - rabbitmq

  # Módulo 2 (Nomes dos serviços alterados para forçar leitura nova)
  pub_0:
    build: ./publisher
    image: sensor_img
    container_name: sensor_ntp
    environment:
      - SENSOR_ID=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - trafego

  pub_a:
    build: ./publisher
    image: sensor_img
    container_name: sensor_a
    environment:
      - SENSOR_ID=A
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - trafego

  pub_b:
    build: ./publisher
    image: sensor_img
    container_name: sensor_b
    environment:
      - SENSOR_ID=B
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - trafego

  # Módulo 3 — Semáforos Inteligentes (Subscribers)
  sub_1:
    build: ./subscriber
    container_name: sub_1
    environment:
      - NODE_ID=1
      - TOTAL_NODES=4
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - trafego

  sub_2:
    build: ./subscriber
    image: subscriber_img
    container_name: sub_2
    environment:
      - NODE_ID=2
      - TOTAL_NODES=4
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - trafego

  sub_3:
    build: ./subscriber
    image: subscriber_img
    container_name: sub_3
    environment:
      - NODE_ID=3
      - TOTAL_NODES=4
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - trafego

  sub_4:
    build: ./subscriber
    image: subscriber_img
    container_name: sub_4
    environment:
      - NODE_ID=4
      - TOTAL_NODES=4
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-guest}
    depends_on:
      - rabbitmq
    networks:
      - trafego

networks:
  trafego:
    driver: bridge

# Módulo 4
#  recovery:
#    build: ./recover
